[project]
name = "fancup-stacks-2026"
description = "FanCup Stacks 2026 is an onchain football prediction, fan voting, and supporter reputation dApp built on the Stacks blockchain using Clarity smart contracts."
authors = ["Bayu Benjamin - github.com/amandaaaaaaew23"]
telemetry = true
cache_dir = "./.cache"
requirements = []

[contracts.fancup-core]
path = "contracts/fancup-core.clar"
clarity_version = 3
epoch = 3.0

[contracts.fancup-badge]
path = "contracts/fancup-badge.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

